# Assignment 1: Bryant Parchinski

## Code Cell Practices From Lesson

In [3]:
A = 5
B = 5.2
C = "True"
D = "A String"
E = '''
A 
multi-line
String
'''
print (A, B, C, D, E)

5 5.2 True A String 
A 
multi-line
String



In [5]:
x = 5
print ("type of variable x:", type(x))
print("x = ",x)

x = "ISC 4551: Data Graphics and Visualization"
print("type of variable x:", type(x))
print("x = ",x)

x = 5.2
print("type of variable x:", type(x))
print("x = ",x)

type of variable x: <class 'int'>
x =  5
type of variable x: <class 'str'>
x =  ISC 4551: Data Graphics and Visualization
type of variable x: <class 'float'>
x =  5.2


In [8]:
a = 5.2
x = "A String "
print(a * x) # Can't multiply unlike type

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:
print("University Of Centrl Florida "+"Orlando") # Conctenation

University Of Centrl Florida Orlando


In [11]:
b = 5
y = 4
z = f'Value of b*y: {b*y}'
print (z)

Value of b*y: 20


In [12]:
z = 'The course name:\tISC 4551'
print(z)
z = r'The course name:\tISC 4551'
print(z)

The course name:	ISC 4551
The course name:\tISC 4551


In [13]:
a = True
print(a)
b = False
print(b)

True
False


In [14]:
print(True*100.2)

100.2


In [15]:
print(False*100.2)

0.0


In [16]:
print(True*"String")

String


In [18]:
print(False*"String")

In [19]:
# A comment
# There is no multiline comment in Python
# But Triple quotes may be used for multi-line comments.

s = """
a = True
print(a)
b = False
print(b)
"""
print (s)


a = True
print(a)
b = False
print(b)



In [20]:
a = int(5.2)
print(a, type(a))
a = int("5")
print(a, type(a))
a = float(5)
print(a, type(a))
a = float("5.2")
print(a, type(a))
a = bool(0)
print(a, type(a))
a = bool(5.2)
print(a, type(a))
a = bool("A string")
print(a, type(a))
a = bool("")
print(a, type(a))

5 <class 'int'>
5 <class 'int'>
5.0 <class 'float'>
5.2 <class 'float'>
False <class 'bool'>
True <class 'bool'>
True <class 'bool'>
False <class 'bool'>


In [21]:
names = ['Jack', 'Jill']
print(names[0])

print (names)

print(len(names))

names[1] = "John"
print(names)

emptyList = [] #or list()
print(len(emptyList))

Jack
['Jack', 'Jill']
2
['Jack', 'John']
0


In [22]:
names = ['Jack', 'Jill']
names.append('Rick')

print (names, len(names))

names.extend(['Kevin', 'Adrian'])
print (names, len(names))

['Jack', 'Jill', 'Rick'] 3
['Jack', 'Jill', 'Rick', 'Kevin', 'Adrian'] 5


In [23]:
eNames = ['Jack', 'Jill'] + ['Kevin', 'Adrian']
print(eNames, len(eNames))

['Jack', 'Jill', 'Kevin', 'Adrian'] 4


In [32]:
coordinates = (2., 5., 1.)     # Note the parenthesis or round brackets.
print(coordinates)
print(coordinates[0], coordinates[1])
print(len(coordinates))

(2.0, 5.0, 1.0)
2.0 5.0
3


In [33]:
coordinates[0] = 3 # the above statement would not work as tuples are immutable

TypeError: 'tuple' object does not support item assignment

In [25]:
emptyTuple = () #tuple()
print(emptyTuple, len(emptyTuple))
oneElemTuple = (1.5, )   
print(oneElemTuple)

() 0
(1.5,)


In [26]:
a = (1.5)
print(a, type(a))
a = (1.5,)
print(a, type(a))

1.5 <class 'float'>
(1.5,) <class 'tuple'>


In [30]:
course = { 
    "number" :  "ISC 4551", 
    "name": "Data Graphics and Visualization",
    "classSize": 92
}
print (course)

{'number': 'ISC 4551', 'name': 'Data Graphics and Visualization', 'classSize': 92}


In [31]:
print (course["number"])

ISC 4551


In [35]:
print(course.keys())

print(course.values())

print(course.items())

dict_keys(['number', 'name', 'classSize'])
dict_values(['ISC 4551', 'Data Graphics and Visualization', 92])
dict_items([('number', 'ISC 4551'), ('name', 'Data Graphics and Visualization'), ('classSize', 92)])


In [38]:
thisset = {"apple", "banana", "cherry"}
print(thisset)

# No duplicate items are allowed in a set
thisset = {"apple", "banana", "cherry", "apple"}
print(thisset)

{'banana', 'cherry', 'apple'}
{'banana', 'cherry', 'apple'}


In [39]:
print("banana" in thisset)

print("pineapple" in thisset)

thisset.add("pineapple")

print("pineapple" in thisset)

# Allows union, intersection, difference and more

True
False
True


In [1]:
import numpy as np
A = [1, 5, 3, 4, 5]
nA = np.array(A)
print(nA, type(nA))
print(nA[0])

[1 5 3 4 5] <class 'numpy.ndarray'>
1


In [2]:
A.append(10)
print(A)

[1, 5, 3, 4, 5, 10]


In [3]:
nA.append(10)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [4]:
A+5

TypeError: can only concatenate list (not "int") to list

In [5]:
print(nA+5)

[ 6 10  8  9 10]


In [6]:
print(nA)

[1 5 3 4 5]


In [7]:
from numpy import random
print(random.randint(100)) # integer random number in the range [0, 100)

print(random.randint(100, size=(5))) # integer random 1D array of size 5

print (random.rand())   # float random number in the range [0, 1)

print(random.rand(5))   # float random array of size 5

16
[26 62 19  3 45]
0.15533674732070213
[0.52957567 0.6356082  0.16472513 0.93163973 0.69023903]


In [8]:
random.uniform()

print(random.uniform(low=0,high=2,size=5)) # uniform distribution in [0,2)

print(random.normal(loc=0,scale = 1, size = 5)) # normal distribution  loc is the mean and scale is the standard deviation

print( random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=5))

print(random.permutation([1,2,3,4,5]))

[1.92276485 1.18847678 0.89496288 0.46372574 0.90379901]
[-0.83209243  0.20747224  0.45175348  0.2321233   1.06951858]
[7 5 7 5 7]
[3 4 5 1 2]


In [9]:
import pandas as pd

student1 = {
 "courses": ["ISC 4551", "CAP 4720"],
 "grades": ["A", "B+"]
}

df = pd.DataFrame(student1)

In [10]:
print(student1)

{'courses': ['ISC 4551', 'CAP 4720'], 'grades': ['A', 'B+']}


In [11]:
print(type(student1), type(df))

<class 'dict'> <class 'pandas.core.frame.DataFrame'>


In [12]:
print(df)

    courses grades
0  ISC 4551      A
1  CAP 4720     B+


In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   courses  2 non-null      object
 1   grades   2 non-null      object
dtypes: object(2)
memory usage: 164.0+ bytes


In [14]:
df.columns

Index(['courses', 'grades'], dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [16]:
df.index = ["I","II"] # Assignment labels to rows

In [17]:
print(df)

     courses grades
I   ISC 4551      A
II  CAP 4720     B+


In [18]:
# Column Access is similar to dictionary access using a key.
print(df["courses"])

I     ISC 4551
II    CAP 4720
Name: courses, dtype: object


In [19]:
print(df["grades"])

I      A
II    B+
Name: grades, dtype: object


In [20]:
# Row access
print(df.loc["I"])

courses    ISC 4551
grades            A
Name: I, dtype: object


In [21]:
print(df.loc["I","courses"])

ISC 4551


In [22]:
print(df.iloc[0,1])

A


In [23]:
print(df.iloc[0]["courses"])

ISC 4551


In [24]:
print(df.iloc[0])

courses    ISC 4551
grades            A
Name: I, dtype: object


In [25]:
df1 = pd.DataFrame({'courses': ['ISC 4551', 'CAP 4720'], 'grades': ['A', 'B+']})
print(df1)

    courses grades
0  ISC 4551      A
1  CAP 4720     B+


In [26]:
print(df1.loc[0])

courses    ISC 4551
grades            A
Name: 0, dtype: object


In [27]:
print(df1.iloc[0])

courses    ISC 4551
grades            A
Name: 0, dtype: object


In [28]:
df = pd.read_csv("data.csv")
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [29]:
print(df.head(5))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [31]:
df.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [32]:
number = 0

In [33]:
#
# if statement
#
if number > 0:
    print('Number is positive.')

#
# if...else statement
#
if number > 0:
    print('Positive number')
else:
    print('Not a Positive number')

#
# if...elif...else statement
#
if number > 0:
    print("Positive number")
elif number == 0:
    print('Zero')
else:
    print('Negative number')

Not a Positive number
Zero


In [34]:
for i in range(5):
    print (i*i)
# The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and stops before a specified number.
# Syntax: range(start, stop, step)

0
1
4
9
16


In [35]:
aList = []
for i in range(5):
    aList.append(i*i)
print(aList)

[0, 1, 4, 9, 16]


In [36]:
aList = [(1,10), (2,20), (3,30)]
for x, y in aList:
    print(x,y)

1 10
2 20
3 30


In [37]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [38]:
[i*i for i in range(5) if i % 2 == 0]

[0, 4, 16]

In [39]:
i = 0
while i < 5:
    print (i)
    i += 1

0
1
2
3
4


In [40]:
def square(num):
    return num * num
print(square(5))

25


In [41]:
for i in [1,2,3]:
    print(f'Square of {i} = {square(i)}')

Square of 1 = 1
Square of 2 = 4
Square of 3 = 9


In [42]:
x = lambda a : a + 10
print(x(5))

15


In [43]:
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))

13
